# Generated by Django 4.1 on 2024-12-19 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "greenhouse",
                    models.CharField(
                        choices=[
                            ("온실 1", "온실 1 (50평)"),
                            ("온실 2", "온실 2 (50평)"),
                            ("온실 3", "온실 3 (50평)"),
                            ("온실 4", "온실 4 (50평)"),
                            ("온실 5", "온실 5 (50평)"),
                            ("온실 6", "온실 6 (50평)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "rental_period",
                    models.CharField(
                        choices=[("개월", "개월"), ("년", "년")], max_length=5
                    ),
                ),
                ("duration", models.PositiveIntegerField()),
                ("name", models.CharField(max_length=100)),
                ("business_plan", models.FileField(upload_to="business_plans/")),
                ("total_price", models.PositiveIntegerField()),
            ],
        ),
    ]
